name: game_ball
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^6.0.1
  camera: ^0.11.0+2
  audioplayers: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/skibidi.png
    - assets/images/bad.jpg
    - assets/images/grandma.png
    - assets/images/atars.jpg
    - assets/music/ski.mp3

